version:  '3.7'

services:

  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./public:/var/www:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    container_name: '${APP_NAME}'
    image: '${APP_NAME}'
    hostname: '${APP_NAME}'
    build:
      context: .
      args:
        user: ${USER_NAME}
        user_id: ${USER_UID}
        application_path: ${APP_PATH}
      dockerfile: ./.docker/php/Dockerfile
    restart: on-failure
    depends_on:
      - db
    user: ${USER_NAME}
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
      - symfony_var:${APP_PATH}/var

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${APP_PATH}/.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  symfony_var:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    driver: bridge
    name: ${APP_NAME}
